name: test
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.2.0
  cupertino_icons: ^1.0.2
  videosdk: ^1.1.3
  http: ^0.13.6
  flutter_vlc_player: ^7.2.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  cloud_firestore: ^4.8.2
  country_picker: ^2.0.20
  pinput: ^2.2.31
  get: ^4.6.5
  google_sign_in: ^6.1.4
  image_picker: ^0.8.4+4
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.0
  firebase_database: ^10.2.3


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


